name: Documentation Update

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Validate Markdown Links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/markdown-link-check-config.json'
          
      - name: Spell Check
        uses: rojopolis/spellcheck-github-actions@0.29.0
        with:
          config_path: .github/workflows/spellcheck-config.yml

  update-index:
    needs: validate-docs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown pyyaml
          
      - name: Update documentation index
        run: |
          python automation/workflows/update_docs_index.py
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update documentation index [skip ci]"
          file_pattern: README.md